# Generated by Django 4.2 on 2024-12-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalhubapp', '0002_remove_booking_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
